name: Build THGJB
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/Users/runner/theos" >> $GITHUB_ENV
      - name: Install SDKs
        run: |
          mkdir -p $THEOS/sdks
          curl -L https://github.com/theos/sdks/archive/master.tar.gz | tar -xz -C $THEOS/sdks --strip-components=1
      - name: Build
        run: |
          export PATH=$PATH:$THEOS/bin
          # Busca el directorio que contiene el Makefile y compila ahí
          PROJECT_DIR=$(find . -name "Makefile" -exec dirname {} \; | head -n 1)
          if [ -z "$PROJECT_DIR" ]; then
            echo "Error: No se encontró ningún Makefile en el repositorio."
            exit 1
          fi
          echo "Compilando en: $PROJECT_DIR"
          cd "$PROJECT_DIR" && make
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./**/packages/*.deb
          if-no-files-found: error

